[project]
name = "building-ai-agents-with-crewai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=1.6.1",
    "crewai-tools>=1.6.1",
    "ipykernel>=7.1.0",
    "openai>=2.14.0",
]
